-- ============================================================
-- Esquema de la base de datos · Mapa del viaje familiar
-- Ejecutar TODO este archivo en Supabase → SQL Editor → New query
-- ============================================================

-- 1) Enum de categorías
create type public.place_category as enum (
  'museo',
  'iglesia',
  'monumento',
  'ruina_arqueologica',
  'parque',
  'paseo_barrio',
  'comida',
  'otro'
);

-- 2) Tabla places
create table public.places (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  city text,
  country text,
  lat double precision,
  lng double precision,
  category public.place_category not null default 'otro',
  description text,
  highlights text,
  opening_hours text,
  reservation_required boolean not null default false,
  reservation_notes text,
  price text,
  assigned_date date,
  must_see boolean not null default false,
  visited boolean not null default false,
  notes text,
  added_by text,
  created_at timestamptz not null default now()
);

-- Índices útiles
create index places_assigned_date_idx on public.places (assigned_date);
create index places_city_idx on public.places (city);
create index places_category_idx on public.places (category);

-- 3) Row Level Security: cualquiera con el link y la anon key lee/escribe.
--    El acceso se controla compartiendo la URL solo con la familia; la anon key
--    protegida por RLS amplía solo estas operaciones en esta tabla.
alter table public.places enable row level security;

drop policy if exists "app_access" on public.places;
create policy "app_access"
  on public.places
  for all
  to anon, authenticated
  using (true)
  with check (true);

-- 4) Realtime: publicar cambios de la tabla
alter publication supabase_realtime add table public.places;

-- 4b) Tabla flights: horas editables de los tramos del itinerario
create table if not exists public.flights (
  id text primary key,               -- clave estable del tramo (ej. 'mad-par-27dic')
  label text not null,               -- título del tramo
  departure_time text,               -- hora de salida (texto libre, ej. '15:30')
  arrival_time text,                 -- hora de llegada
  flight_number text,                -- número de vuelo (ej. AV254)
  notes text,                        -- notas libres
  updated_by text,                   -- quién editó por última vez
  updated_at timestamp with time zone default now()
);
alter table public.flights enable row level security;
drop policy if exists "flights_access" on public.flights;
create policy "flights_access"
  on public.flights
  for all
  to anon, authenticated
  using (true)
  with check (true);
alter publication supabase_realtime add table public.flights;

-- ============================================================
-- 5) DATOS PRECARGADOS (los mismos del archivo src/seed.js)
--    insert solo si la tabla está vacía
-- ============================================================
insert into public.places
  (name, city, country, lat, lng, category, description, highlights, opening_hours,
   reservation_required, reservation_notes, price, assigned_date, must_see, notes, added_by)
values
  -- ROMA
  ('Museos Vaticanos + Capilla Sixtina','Roma','Italia',41.9065,12.4536,'museo',
   'Uno de los mayores museos del mundo: miles de obras coleccionadas por los papas a lo largo de siglos, desde antigüedades egipcias y romanas hasta Renacimiento. El recorrido termina en la Capilla Sixtina, con el techo de Miguel Ángel y El Juicio Final.',
   'Capilla Sixtina (techo y Juicio Final de Miguel Ángel), Estancias de Rafael, La Escuela de Atenas, Galeria de los Mapas, Laocoonte y sus hijos, Apolo del Belvedere, espiral de Bramante.',
   'Lun–Sáb 8:00–19:00 (última entrada 16:00); domingos cerrado salvo último domingo de mes. Verificar antes del viaje.',
   true,'Reserva online obligatoria de franja horaria; se agota con días de antelación. Entrada base ~€20 + reserva €5. Verificar precios antes del viaje.',
   '€20 + €5 reserva (aprox. — verificar)','2027-01-05',true,
   'Llegar al menos 15 min antes de la franja. Entrada por el Viale Vaticano. Dos horas mínimo para la Sixtina.','Precarga'),
  ('Basílica de San Pedro','Roma','Italia',41.9022,12.4539,'iglesia',
   'La iglesia más grande del cristianismo, sobre la tumba de San Pedro. Cúpula de Miguel Ángel, la Piedad, baldaquino de Bernini y plaza elíptica con columnata. Entrada gratuita a la basílica; la cúpula y el tesoro se pagan aparte.',
   'La Piedad de Miguel Ángel, cúpula (551 escalones a pie o 320 en ascensor+escalera), baldaquino de Bernini, estatua de San Pedro con pies besados, Sacra Grotte bajo la basílica.',
   'Basílica: Abr–Sep 7:00–19:00, Oct–Mar 7:00–18:30. Cúpula: 8:00–17:00 (verificar). Cerrada miércoles por audiencia papal (mañana).',
   false,'Fila de seguridad gratuita (puede ser de 30–90 min). La cúpula sí se compra al llegar: ~€10 a pie / €15 con ascensor. Verificar.',
   'Gratis (cúpula €10–15 — verificar)','2027-01-05',true,
   'Código de vestimenta estricto: hombros y rodillas cubiertos. Combinar con los Museos Vaticanos el mismo día.','Precarga'),
  ('Foro Romano y Palatino','Roma','Italia',41.8925,12.4853,'ruina_arqueologica',
   'El corazón político, religioso y comercial de la Roma antigua durante mil años. Templos, basílicas, arcos triunfales y la Vía Sacra, con el Palatino (cuna de Roma) en la colina.',
   'Templo de Saturno, Arco de Septimio Severo, Curia Julia, Arco de Tito, Casa de las Vestales, vista desde el Palatino.',
   'Todos los días 9:00–16:30/19:15 según temporada (última entrada 1h antes). Cerrado 1 ene y 25 dic. Verificar.',
   true,'Entrada combinada Coliseo + Foro + Palatino (~€18, válida 24h). Reserva online recomendada ~€2. Verificar.',
   '€18 (combinada Coliseo — verificar)','2027-01-06',true,
   'Entrar por Via di San Gregorio o Via dei Fori Imperiali. 2–3 horas. Llevar agua.','Precarga'),
  ('Circo Máximo','Roma','Italia',41.8858,12.4854,'ruina_arqueologica',
   'El estadio más grande de la antigüedad: 621 × 118 m y aforo de ~150.000 espectadores para las carreras de cuadrigas. Hoy parque arqueológico con la pista y el palco imperial.',
   'Trazado de la spina, Torretta Valadier con vista, restos arqueológicos.',
   'Parque: siempre abierto. Sección arqueológica: Mar–Dom 10:00–19:00 aprox. Verificar.',
   false,'El parque es gratuito; la sección expositiva ~€5. Verificar.',
   'Gratis (interior ~€5 — verificar)','2027-01-06',false,
   'Entre el Foro y el Aventino. 30–40 min.','Precarga'),
  ('Castel Sant''Angelo','Roma','Italia',41.9031,12.4663,'monumento',
   'Mausoleo de Adriano (siglo II) reconvertido en fortaleza papal y prisión, conectado con el Vaticano por el Passetto di Borgo. Salas renacentistas y terraza panorámica sobre el Tíber.',
   'Terraza panorámica, Passetto, apartamentos de Julio II, loggias de Giulio Romano.',
   'Todos los días 9:00–19:30 (última entrada 18:30). Verificar.',
   false,'Entrada ~€16–17 (verificar); sin reserva obligatoria.',
   '€16–17 (aprox. — verificar)','2027-01-07',false,
   'Cruzando el puente con los ángeles de Bernini. Buena parada hacia/desde el Vaticano.','Precarga'),
  ('Chiesa di Sant''Ignazio di Loyola','Roma','Italia',41.8992,12.4786,'iglesia',
   'Iglesia jesuita barroca famosa por su techo: el falso domo trompe-l''œil de Andrea Pozzo y la gloria de San Ignacio que se funde con el cielo.',
   'Falso domo de Pozzo, Apoteosis de San Ignacio, espejo para ver el techo.',
   'Todos los días 7:30–19:00 aprox. Verificar.',
   false,'Gratis; donativo sugerido €1–2.',
   'Gratis','2027-01-07',false,
   'A 2 min de Trevi y del Panteón. Mejor por la mañana.','Precarga'),
  ('Fontana di Trevi','Roma','Italia',41.9009,12.4833,'monumento',
   'La fuente barroca más famosa del mundo, terminal del acueducto Acqua Vergine. Tradición: una moneda sobre el hombro derecho para volver a Roma.',
   'Océano de Pietro Bracci, caballos calmados y agitados, monedas para Caritas.',
   '24/7. Prohibido bañarse. Verificar medidas de acceso en horas punta.',
   false,'Gratuita. Mejor al amanecer o de noche tarde.',
   'Gratis','2027-01-07',true,
   'Cuidado con carteristas. Combinar con Panteón y Piazza Navona.','Precarga'),
  ('Basilica di San Giovanni in Laterano','Roma','Italia',41.8859,12.5066,'iglesia',
   'La catedral de Roma y «madre de todas las iglesias», más antigua que San Pedro. Fachada de Galilei, estatuas de los apóstoles y baldaquino gótico.',
   'Baldaquino gótico, claustro medieval, Scala Santa enfrente, bautisterio octogonal.',
   'Todos los días 7:00–18:30; claustro 9:00–18:00. Verificar.',
   false,'Gratis. Vestimenta apropiada.',
   'Gratis','2027-01-08',false,
   'Metro A San Giovanni. Combina con Scala Santa.','Precarga'),
  ('Caffetteria Italia al Vittoriano','Roma','Italia',41.8953,12.4823,'comida',
   'Cafetería en la cima del Altare della Patria con terraza sobre los Foros Imperiales. Vista sin pagar mirador.',
   'Terraza sobre los Foros, acceso directo sin museo.',
   'Todos los días ~9:00–19:00. Verificar.',
   false,'Sin reserva; precios de cafetería turística.',
   '€ (cappuccino + cornetto ~€5–7)','2027-01-08',false,
   'Truco: ver los Foros desde arriba gratis.','Precarga'),
  ('Pompei · Sitio arqueológico','Pompeya','Italia',40.7497,14.4869,'ruina_arqueologica',
   'La ciudad romana sepultada por el Vesubio en el 79 d.C., congelada en el tiempo: calzadas, termas, villas y el anfiteatro. 44 hectáreas visitables.',
   'Casa del Fauno, Villa de los Misterios, termas del Foro, anfiteatro, moldes de víctimas.',
   'Todos los días 9:00–17:00 en invierno (última entrada 15:30). Cerrado 1 ene y 25 dic. Verificar.',
   true,'Reserva online recomendada (~€19 + €2). Circumvesuviana: Napoli Centrale → Pompei Scavi (36 min). Verificar.',
   '€19 + €2 reserva (aprox. — verificar)','2027-01-07',true,
   'Zapatillas cómodas, agua, gorra. 4–5 horas. Entrada por Porta Marina.','Precarga'),

  -- FLORENCIA
  ('Cattedrale di Santa Maria del Fiore (Duomo)','Florencia','Italia',43.7731,11.2560,'iglesia',
   'La catedral de Florencia con la cúpula de Brunelleschi, obra maestra del Quattrocento. Complejo con baptisterio, campanile, cripta y museo.',
   'Cúpula de Brunelleschi (463 escalones, con reserva), puertas del Paraíso, frescos de la cúpula.',
   'Catedral Lun–Sáb 10:15–15:30. Cúpula y baptisterio: horarios aparte. Verificar.',
   true,'La cúpula SOLO con reserva de franja (se agota antes) en ilduomo.firenze.it. Brunelleschi Pass ~€30. Verificar.',
   '€30 (Brunelleschi Pass — verificar)','2027-01-04',true,
   'Reservar la cúpula con mucha antelación.','Precarga'),
  ('Galleria dell''Accademia (David)','Florencia','Italia',43.7762,11.2581,'museo',
   'Museo del David de Miguel Ángel (1504) y otras esculturas suyas, con tablas góticas e instrumentos musicales antiguos.',
   'David (5,17 m), Prisioneros, San Mateo, instrumentos del Conservatorio.',
   'Mar–Dom 8:15–18:50; lunes cerrado. Verificar.',
   true,'Reserva online recomendada (~€16 + €4). Verificar.',
   '€16 + €4 reserva (aprox. — verificar)','2027-01-04',true,
   '1–1,5 h. Cerca de San Marco y Mercato Centrale.','Precarga'),
  ('Galleria degli Uffizi','Florencia','Italia',43.7678,11.2552,'museo',
   'La gran pinacoteca de los Medici: el mejor recorrido del Renacimiento italiano, con loggia sobre el Arno.',
   'Nacimiento de Venus y Primavera de Botticelli, Anunciación de Leonardo, Venus de Urbino, Caravaggio.',
   'Mar–Dom 8:15–18:30; lunes cerrado. Verificar.',
   true,'Reserva de franja obligatoria en temporada (~€25 + €4). Verificar.',
   '€25 + €4 reserva (aprox. — verificar)','2027-01-04',true,
   '2,5–3 h. Reservar con semanas de antelación.','Precarga'),
  ('Ponte Vecchio','Florencia','Italia',43.7679,11.2531,'monumento',
   'El puente medieval sobre el Arno (1345) cubierto de orfebres; sobrevivió intacto a la II Guerra Mundial.',
   'Joyerías, busto de Cellini, vista desde el Ponte Santa Trinita.',
   'Siempre abierto (peatonal).',
   false,'Gratis cruzarlo.',
   'Gratis','2027-01-04',false,
   'Atardecer mágico. Carteristas.','Precarga'),
  ('Piazzale Michelangelo','Florencia','Italia',43.7623,11.2646,'paseo_barrio',
   'La terraza panorámica sobre Florencia: vista de postal del Duomo, Palazzo Vecchio y las colinas; copia en bronce del David.',
   'Panorama 180°, San Miniato al Monte al lado, atardeceres legendarios.',
   'Siempre abierto.',
   false,'Gratis.',
   'Gratis','2027-01-04',false,
   'Ir al atardecer; abrigo en enero.','Precarga'),

  -- VENECIA
  ('Basilica di San Marco','Venecia','Italia',45.4345,12.3388,'iglesia',
   'La basílica dorada de Venecia: arte bizantino con 8.000 m² de mosaicos, Pala d''Oro y los caballos de bronce.',
   'Mosaicos bizantinos, Pala d''Oro, Caballos de San Marcos, loggia con vista a la Piazza.',
   'Lun–Sáb 9:45–17:00, Dom 14:00–17:00. Verificar.',
   true,'Entrada €3 + reserva €3 (evita la fila). Pala €5, museo €7. Verificar.',
   '€3 + extras (verificar)','2027-01-03',true,
   'Vestimenta apropiada. Sin maletas.','Precarga'),
  ('Palazzo Ducale','Venecia','Italia',45.4348,12.3396,'museo',
   'El palacio de los dux: gótico veneciano con salones de Tintoretto y Veronés, prisiones y el Puente de los Suspiros.',
   'Sala del Maggior Consiglio, Escalera de Oro, Ponte dei Sospiri, armería.',
   'Todos los días 9:00–18:00. Verificar.',
   true,'Entrada ~€30 con reserva online recomendada. Tour «Secret Itineraries» aparte. Verificar.',
   '€30 (aprox. — verificar)','2027-01-03',true,
   '2 h. Frente a la Basílica.','Precarga'),
  ('Canal Grande en vaporetto (línea 1)','Venecia','Italia',45.4380,12.3358,'paseo_barrio',
   'Recorrido en vaporetto por la «S» del Gran Canal, flanqueada por palacios del Renacimiento, de Piazzale Roma a San Marco.',
   'Ca'' d''Oro, Puente de Rialto, Santa Maria della Salute.',
   'Línea 1: cada 12 min, 5:00–23:30. Verificar.',
   false,'Billete único ~€9,50 (75 min) o pase ACTV 24h/72h. Verificar.',
   '€9,50 viaje (pases disponibles)','2027-01-03',false,
   'Subir en la proa del vaporetto.','Precarga'),
  ('Burano','Venecia','Italia',45.4856,12.4167,'paseo_barrio',
   'Isla de la laguna famosa por sus casas de colores intensos, el encaje de bolillos y la torre inclinada.',
   'Casas multicolores, torre inclinada de San Martino, Museo del Merletto.',
   'Siempre accesible (vaporetto línea 12, ~42 min).',
   false,'Requiere billete de vaporetto (pase ACTV).',
   'Transporte vaporetto','2027-01-03',false,
   'Medio día. Combinar con Murano si hay tiempo.','Precarga'),

  -- VERONA
  ('Arena di Verona','Verona','Italia',45.4392,10.9299,'ruina_arqueologica',
   'El anfiteatro romano mejor conservado del mundo (siglo I), aún activo para la ópera: 30.000 espectadores.',
   'Anillo exterior, cavea intacta, acústica legendaria.',
   'Todos los días 8:30–19:30; reducido en montajes. Verificar.',
   false,'Entrada ~€12–14; en enero sin reserva suele bastar. Verificar.',
   '€12–14 (aprox. — verificar)','2027-01-02',true,
   'Pausa perfecta del tren Milán→Venecia. Centro histórico a 10 min a pie.','Precarga'),

  -- MILÁN
  ('Arco della Pace','Milán','Italia',45.4742,9.1717,'monumento',
   'Arco triunfal neoclásico en la puerta del Parco Sempione, coronado con la cuadriga de la Paz; iniciado bajo Napoleón.',
   'Cuadriga de bronce, relieves, vista desde el Sempione, aperitivo en Corso Sempione.',
   'Siempre accesible (plaza abierta).',
   false,'Gratis.',
   'Gratis','2027-01-02',false,
   'Combinar con Parco Sempione y Castello Sforzesco. Metro: Moscova o Lanza.','Precarga'),

  -- PARÍS
  ('Torre Eiffel','París','Francia',48.8584,2.2945,'monumento',
   'El icono de hierro de 330 m (1889). Tres plantas visitables; brillo de 20.000 bombillas cada hora al anochecer.',
   'Cumbre, suelo de cristal, parpadeo dorado nocturno, Champ de Mars.',
   'Todos los días 9:00–0:45. Verificar.',
   true,'Reserva online de franja muy recomendada (se agota con semanas). Cumbre ~€29, 2ª planta ~€18. Verificar.',
   '€18–29 (aprox. — verificar)','2026-12-28',true,
   'Reservar con 60 días de antelación. Vista gratuita: Trocadéro.','Precarga'),
  ('Museo del Louvre','París','Francia',48.8606,2.3376,'museo',
   'El museo más visitado del mundo: antiguo palacio real con 35.000 obras, de Antigüedades a pintura europea.',
   'Mona Lisa, Venus de Milo, Victoria de Samotracia, Códice de Hammurabi.',
   '9:00–18:00; viernes hasta 21:45; martes cerrado. Verificar.',
   true,'Reserva online de franja obligatoria. ~€22. Verificar.',
   '€22 (aprox. — verificar)','2026-12-29',true,
   'Entrar por Carrousel. 3 h mínimas. Denon se satura.','Precarga'),
  ('Palacio de Versalles','Versalles','Francia',48.8049,2.1204,'monumento',
   'El palacio de Luis XIV: Galería de los Espejos, jardines de Le Nôtre y el Grand Trianon. Patrimonio de la Humanidad.',
   'Galería de los Espejos, apartamentos reales, jardines, Hameau de la Reina.',
   'Palacio 9:00–18:30 (cerrado lunes); jardines 8:00–18:30. Verificar.',
   true,'Reserva online de franja obligatoria (~€21; Passport ~€32). RER C (40 min). Verificar.',
   '€21–32 (aprox. — verificar)','2026-12-30',true,
   'Día completo. Abrigo para los jardines en invierno.','Precarga'),
  ('Arco del Triunfo','París','Francia',48.8738,2.2950,'monumento',
   'El arco triunfal más grande del mundo (50 m), con la Tumba del Soldado Desconocido y terraza sobre los 12 bulevares.',
   'Terraza panorámica, La Marsellesa en relieve, llama cada noche.',
   'Todos los días 10:00–22:30. Verificar.',
   false,'Terraza ~€13–16; gratis con Paris Museum Pass. Subir por el paso subterráneo. Verificar.',
   '€13–16 (aprox. — verificar)','2026-12-31',false,
   'Vista nocturna de la Torre Eiffel parpadeante.','Precarga'),
  ('Tumba de Napoleón (Les Invalides)','París','Francia',48.8568,2.3123,'monumento',
   'El Dôme de los Inválidos custodia el sarcófago de cuarcita roja de Napoleón, más el Museo del Ejército.',
   'Sarcófago de Napoleón, cúpula dorada, Museo del Ejército.',
   'Todos los días 10:00–18:00. Cerrado 1 ene. Verificar.',
   false,'Entrada ~€15; gratis con Paris Museum Pass. Verificar.',
   '€15 (aprox. — verificar)','2026-12-31',false,
   '2 h. Cerca: Museo Rodin y Rue Cler.','Precarga'),
  ('La Sorbona','París','Francia',48.8490,2.3435,'monumento',
   'La universidad más antigua de Francia (1257), corazón del Barrio Latino. El anfiteatro y la capilla se visitan con guía.',
   'Grand Amphithéâtre, capilla del siglo XVII, Place de la Sorbonne.',
   'Visita guiada solo con reserva (sábados). Verificar.',
   true,'Visita guiada oficial con reserva (~€12–15, sábados). Verificar.',
   '€12–15 (visita guiada — verificar)','2026-12-31',false,
   'Si no hay visitas, pasear el Barrio Latino basta.','Precarga'),
  ('La Bastilla (Place de la Bastille)','París','Francia',48.8532,2.3692,'monumento',
   'La plaza de la fortaleza tomada el 14 de julio de 1789. Hoy la Colonne de Juillet y cimientos visibles en el metro.',
   'Colonne de Juillet, cimientos en el andén (línea 5), Port de l''Arsenal.',
   'Siempre accesible.',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Combinar con Marais y Canal Saint-Martin.','Precarga'),
  ('Catedral de Notre-Dame','París','Francia',48.8530,2.3499,'iglesia',
   'La catedral gótica más famosa del mundo, reabierta en 2024 tras el incendio, con interior restaurado espectacular.',
   'Rosetones del XIII, coro restaurado, órgano Cavaillé-Coll, cripta arqueológica.',
   'Todos los días 7:45–19:00 (jueves hasta 22:00). Verificar.',
   false,'Entrada gratuita con fila de seguridad; torres con reserva (~€16). Verificar.',
   'Gratis (torres ~€16 — verificar)','2026-12-29',true,
   'Ir temprano o después de las 17h.','Precarga'),
  ('Église Saint-Sulpice','París','Francia',48.8510,2.3336,'iglesia',
   'La segunda iglesia más grande de París: clasicista, con murales de Delacroix y el gnómon astronómico.',
   'Capilla de los Ángeles (Delacroix), gnómon, órgano monumental.',
   'Todos los días 7:30–19:30. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-30',false,
   'Cerca del Jardin du Luxembourg.','Precarga'),
  ('Église Saint-Eustache','París','Francia',48.8662,2.3469,'iglesia',
   'Iglesia gótico-renacentista en Les Halles: nave de 105 m, órganos legendarios y el tríptico de Couture.',
   'Órgano de 8.000 tubos, Head of Karma de Huang Yong Ping, vitrales contemporáneos.',
   'Lun–Sáb 9:30–19:00, Dom 9:00–19:00. Verificar.',
   false,'Gratis. Conciertos de órgano algunos domingos.',
   'Gratis','2026-12-29',false,
   'A 5 min del Louvre y Pompidou.','Precarga'),
  ('La Madeleine','París','Francia',48.8701,2.3245,'iglesia',
   'Iglesia con forma de templo griego (52 columnas corintias) en el eje Concorde; napoleónica y terminada como iglesia.',
   'Frontón del Juicio Final, cúpula con mosaicos, órganos.',
   'Todos los días 9:30–19:00. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-30',false,
   'Cerca de la Place de la Concorde.','Precarga'),
  ('Musée d''Art Moderne de Paris','París','Francia',48.8636,2.3020,'museo',
   'Museo municipal del Palais de Tokyo con Fauvismo, Dada y Escuela de París: La Fée Électricité de Dufy.',
   'La Fée Électricité, Matisse in situ, Picasso, Modigliani, terraza con la Torre Eiffel.',
   'Mar–Dom 10:00–18:00; lunes cerrado. Verificar.',
   false,'Colección permanente GRATUITA; temporales de pago. Verificar.',
   'Gratis (permanente)','2026-12-31',false,
   'Muy subestimado y sin colas.','Precarga'),
  ('Musée Fragonard','París','Francia',48.8780,2.3110,'museo',
   'Museo de la casa de perfumes Fragonard: hôtel particular con colección de perfumería y visitas guiadas gratuitas.',
   'Visita guiada gratuita (~30 min), alambique de cobre, tienda con descuento.',
   'Lun–Sáb 9:00–18:00. Verificar.',
   false,'Gratis. Visita guiada a horas fijas (consultar).',
   'Gratis','2026-12-30',false,
   'Parada breve cerca de la Ópera Garnier.','Precarga'),
  ('Jardin du Luxembourg','París','Francia',48.8462,2.3372,'parque',
   'El jardín del Senado (1612): parterre francés, estanque con veleros, estatuas de reinas y Fuente Médici.',
   'Grand Bassin, Medici Fountain, Palais du Luxembourg, vista del Panteón.',
   'Todos los días ~7:30–anochecer. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-30',false,
   'Combina con Saint-Sulpice y Saint-Germain.','Precarga'),
  ('Jardin des Tuileries','París','Francia',48.8635,2.3275,'parque',
   'El jardín francés más clásico de París, entre el Louvre y la Concorde, con el Orangerie en un extremo.',
   'Grand Bassin Rond, Orangerie (Monet), esculturas al aire libre.',
   'Todos los días ~7:00–19:30. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-29',false,
   'Paseo obligatorio entre Louvre y Concorde.','Precarga'),
  ('Parc des Buttes-Chaumont','París','Francia',48.8806,2.3820,'parque',
   'El parque romántico más dramático de París (1867): acantilados, cascada, grotto y el templo de la Sibila.',
   'Temple de la Sibylle, puente colgante, cascada y grotto, vistas 360°.',
   'Todos los días ~7:00–21:00. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Menos turístico y muy local. Cerca del Canal Saint-Martin.','Precarga'),
  ('Parc Monceau','París','Francia',48.8797,2.3095,'parque',
   'Jardín anglo-chino del XVIII con caprichos: pirámide, columnata corintia y puente egipcio.',
   'Columnata, pirámide, puente egipcio, estatua de Chopin.',
   '~7:00–22:00. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-30',false,
   'Barrio elegante para pasear.','Precarga'),
  ('Parc de la Villette','París','Francia',48.8902,2.3895,'parque',
   'El parque más vanguardista de París (Tschumi, 1987): follies rojas, jardines temáticos y la Géode.',
   'Follies rojas, jardín del Dragon, Cité des Sciences, La Géode.',
   'Siempre accesible. Museos con horario propio.',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Lejos del centro: ir si hay tiempo.','Precarga'),
  ('Promenade Plantée (Coulée Verte)','París','Francia',48.8478,2.3880,'parque',
   'Viaducto ferroviario convertido en jardín elevado (4,5 km): el original que inspiró la High Line de NY.',
   'Viaduc des Arts, rosaleda, bambúes, vistas de azoteas.',
   'Todos los días ~7:00–21:30. Verificar.',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Entrar por la Avenue Daumesnil cerca de la Bastilla.','Precarga'),
  ('Bois de Boulogne','París','Francia',48.8642,2.2485,'parque',
   'El gran bosque-oeste de París (846 ha): lagos, jardines de Bagatelle y la Fondation Louis Vuitton.',
   'Jardin de Bagatelle, Fondation Louis Vuitton, Lac Inférieur.',
   'Siempre accesible; jardines con horario propio.',
   false,'Gratis (jardines y museos aparte). No entrar de noche en zonas apartadas.',
   'Gratis','2026-12-31',false,
   'Fondation Louis Vuitton merece reserva aparte.','Precarga'),
  ('Puente Alexandre III','París','Francia',48.8639,2.3131,'monumento',
   'El puente más ornamentado de París (1900): ángeles, ninfas, caballos alados y faroles Art Nouveau.',
   'Pegasos, ninfas de la Sena y del Neva, vista de la Torre Eiffel.',
   'Siempre accesible.',
   false,'Gratis.',
   'Gratis','2026-12-30',false,
   'Foto clásica al atardecer. Petit Palais (gratis) al lado.','Precarga'),
  ('Pont des Arts','París','Francia',48.8583,2.3375,'monumento',
   'El puente peatonal del Institut al Louvre: la sala de estar de París, con músicos y pintores.',
   'Vista frontal de Notre-Dame, atardecer sobre el Sena, bateaux debajo.',
   'Siempre accesible.',
   false,'Gratis.',
   'Gratis','2026-12-29',false,
   'Sitarse con un crepe; prohibido el candado desde 2015.','Precarga'),
  ('Rue Crémieux','París','Francia',48.8476,2.3690,'paseo_barrio',
   'Callejón peatonal cerca de Gare de Lyon: casitas de colores pastel con nombres poéticos pintados.',
   'Fachadas rosa, azul y verde, adoquines, plantas.',
   'Siempre accesible (peatonal).',
   false,'Gratis. Respetar a los vecinos: es residencial.',
   'Gratis','2026-12-31',false,
   '10–15 min de parada fotográfica. Cerca de la Coulée Verte.','Precarga'),
  ('Cour Napoléon (patio del Louvre)','París','Francia',48.8611,2.3364,'monumento',
   'El gran patio del Louvre con la pirámide de vidrio de I. M. Pei, flanqueada por las alas del museo.',
   'Pirámide (673 rombos), pirámide invertida, Arco del Carrousel, vista nocturna.',
   'Siempre accesible (patio público).',
   false,'Gratis. La pirámide de noche es un clásico.',
   'Gratis','2026-12-29',false,
   'No confundir con la entrada al museo (requiere reserva).','Precarga'),
  ('Palais-Royal','París','Francia',48.8637,2.3370,'paseo_barrio',
   'Palacio con jardín público y arcadas del XVIII junto al Louvre, con las Columnas de Buren.',
   'Colonnes de Buren, jardín con fuentes, Galerie de Valois, Comédie-Française.',
   'Jardín ~7:30–anochecer.',
   false,'Gratis.',
   'Gratis','2026-12-29',false,
   'Oasis de silencio a 3 min del Louvre.','Precarga'),
  ('Hôtel de Ville','París','Francia',48.8566,2.3522,'monumento',
   'El ayuntamiento de París: palacio renacentista con 108 estatuas; su plaza se vuelve pista de hielo en invierno.',
   'Fachada con estatuas, pista de hielo invernal, historia de la Liberación.',
   'Exterior siempre; pista de hielo dic–mar. Verificar.',
   false,'Exterior y plaza gratis; pista gratuita con patines propios.',
   'Gratis (exterior)','2026-12-29',false,
   'Si coincide, patinar con vistas al Sena.','Precarga'),
  ('Place de la Concorde','París','Francia',48.8656,2.3211,'monumento',
   'La plaza mayor de París: obelisco de Luxor de 3.300 años, fuentes y el eje histórico hacia el Arco del Triunfo.',
   'Obelisco de Luxor, Fontaine des Mers y des Fleuves, vista del eje.',
   'Siempre accesible.',
   false,'Gratis. Cuidado con el tráfico al cruzar.',
   'Gratis','2026-12-29',false,
   'Paso natural entre Madeleine, Tuileries y Campos Elíseos.','Precarga'),
  ('Canal Saint-Martin','París','Francia',48.8709,2.3661,'paseo_barrio',
   'El canal (1825) con esclusas y puentes giratorios, orillas de picnic, boutiques vintage y cafés.',
   'Esclusas, Quai de Valmy, Le Comptoir Général, tiendas vintage.',
   'Orillas siempre accesibles.',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Caminar de la Bastilla a la Villette (~40 min).','Precarga'),
  ('Barrio Latino','París','Francia',48.8470,2.3430,'paseo_barrio',
   'El barrio universitario desde la Edad Media: Sorbona, cafés históricos, Panteón y callejuelas medievales.',
   'Panteón, Shakespeare and Company, Rue Mouffetard, Arenas de Lutecia.',
   'Siempre accesible (barrio).',
   false,'Gratis pasear; museos y Panteón con entrada.',
   'Gratis','2026-12-31',false,
   'Cena en Rue Mouffetard.','Precarga'),
  ('Shakespeare and Company','París','Francia',48.8530,2.3479,'otro',
   'La librería anglofona más famosa del mundo (1951): laberinto de estanterías, piano de pie y gatos.',
   'Piano de pie, sello gratis en compras, café adjunto, junto al Petit Pont.',
   'Todos los días 10:00–22:00 aprox. Verificar.',
   false,'Gratis entrar; fila en temporada alta.',
   'Gratis (libros aparte)','2026-12-29',false,
   'A 2 min de Notre-Dame. Tradición familiar: comprar una novela.','Precarga'),
  ('Arte urbano de Belleville','París','Francia',48.8722,2.3830,'paseo_barrio',
   'El barrio contracultural convertido en capital del street art parisino: murales gigantes y collages.',
   'Rue Denoyez, murales de la Rue de Belleville, vista del Parc de Belleville.',
   'Siempre accesible (barrio).',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Combinar con Buttes-Chaumont.','Precarga'),
  ('Murales del distrito 13','París','Francia',48.8280,2.3720,'paseo_barrio',
   'El Boulevard Vincent Auriol y alrededores, galería de street art a cielo abierto del 13º.',
   'Murales de Inti, D*Face, Seth, Obey; Rue Jeanne d''Arc.',
   'Siempre accesible (calles).',
   false,'Gratis.',
   'Gratis','2026-12-31',false,
   'Metro Nationale o BnF.','Precarga'),
  ('Le Marais','París','Francia',48.8590,2.3600,'paseo_barrio',
   'El barrio medieval de moda: Place des Vosges, boutiques, falafel en Rue des Rosiers y el Musée Picasso.',
   'Place des Vosges, Rue des Rosiers, Marché des Enfants Rouges, Musée Picasso.',
   'Siempre accesible (barrio).',
   false,'Gratis pasear.',
   'Gratis','2026-12-29',false,
   'Helado Amorino o Berthillon (isla Saint-Louis al lado).','Precarga'),
  ('Rue Montorgueil','París','Francia',48.8673,2.3472,'comida',
   'Calle peatonal gastronómica desde el siglo XIV: fromageries, boulangeries y la pâtisserie Stohrer (1730).',
   'Stohrer (baba au rhum), charcuterías, ostras y vino al paseo.',
   'Tiendas ~8:00–20:00; restaurantes hasta la noche. Verificar.',
   false,'Gratis pasear; comer según presupuesto.',
   '€ (según consumo)','2026-12-29',false,
   'Ideal para desayuno o merienda. Cerca de Pompidou.','Precarga'),

  -- MADRID (referencia)
  ('Madrid · llegada y vuelta (referencia)','Madrid','España',40.4168,-3.7038,'otro',
   'Nodo del viaje: llegada el 26 dic, vuelo a París el 27, regreso de Roma el 9 ene (18:30) y salida final el 10 (15:30).',
   'Por definir según horarios finales de vuelos y hotel.',
   '—',
   false,'',
   '—',null,false,
   'Días de transición. Reservar traslado aeropuerto y hotel.','Precarga');
