// Lugares precargados con información pública de referencia.
// Horarios y precios: verificar en las web oficiales antes del viaje.
export const SEED_PLACES = [
  // ───────────────────────── ROMA ─────────────────────────
  {
    name: 'Museos Vaticanos + Capilla Sixtina', city: 'Roma', country: 'Italia',
    lat: 41.9065, lng: 12.4536, category: 'museo',
    description: 'Uno de los mayores museos del mundo: miles de obras coleccionadas por los papas a lo largo de siglos, desde antigüedades egipcias y romanas hasta Renacimiento. El recorrido termina en la Capilla Sixtina, con el techo de Miguel Ángel y El Juicio Final.',
    highlights: 'Capilla Sixtina (techo y Juicio Final de Miguel Ángel), Estancias de Rafael, La Escuela de Atenas, Galeria de los Mapas, Laocoonte y sus hijos, Apolo del Belvedere, espiral de Bramante.',
    opening_hours: 'Lun–Sáb 8:00–19:00 (última entrada 16:00); domingos cerrado salvo último domingo de mes. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online obligatoria de franja horaria; se agota con días de antelación. Entrada base ~€20 + reserva €5. Verificar precios antes del viaje.',
    price: '€20 + €5 reserva (aprox. — verificar)',
    assigned_date: '2027-01-05', must_see: true,
    notes: 'Llegar al menos 15 min antes de la franja. Entrada por el Viale Vaticano. Dos horas mínimo para la Sixtina.',
    added_by: 'Precarga',
  },
  {
    name: 'Basílica de San Pedro', city: 'Roma', country: 'Italia',
    lat: 41.9022, lng: 12.4539, category: 'iglesia',
    description: 'La iglesia más grande del cristianismo, sobre la tumba de San Pedro. Cúpula de Miguel Ángel, la Piedad, baldaquino de Bernini y plaza elíptica con columnata. Entrada gratuita a la basílica; la cúpula y el tesoro se pagan aparte.',
    highlights: 'La Piedad de Miguel Ángel, cúpula (551 escalones a pie o 320 en ascensor+escalera), baldaquino de Bernini, estatua de San Pedro con pies besados, Sacra Grotte bajo la basílica.',
    opening_hours: 'Basílica: Abr–Sep 7:00–19:00, Oct–Mar 7:00–18:30. Cúpula: 8:00–17:00 (verificar). Cerrada miércoles por audiencia papal (mañana).',
    reservation_required: false,
    reservation_notes: 'Fila de seguridad gratuita (puede ser de 30–90 min). La cúpula sí se reserva/compra al llegar: ~€10 a pie / €15 con ascensor. Verificar.',
    price: 'Gratis (cúpula €10–15 — verificar)',
    assigned_date: '2027-01-05', must_see: true,
    notes: 'Código de vestimenta estricto: hombros y rodillas cubiertos. Combinar con los Museos Vaticanos el mismo día.',
    added_by: 'Precarga',
  },
  {
    name: 'Augusto de Prima Porta (Museos Vaticanos)', city: 'Roma', country: 'Italia',
    lat: 41.9065, lng: 12.4545, category: 'museo',
    description: 'Estatua del emperador Augusto en pose de orador, hallada en Prima Porta en 1863. Obra emblemática del arte propagandístico romano, con pecho decorado con relieves alegóricos y descendiente del Doríforo de Policleto. Se exhibe en la sala Braccio Nuovo (Chiaramonti).',
    highlights: 'Coraza con la devolución de los estandartes de Craso por los partos, cupido montado en delfín a sus pies, luego canonizada en copias por todo el imperio.',
    opening_hours: 'Mismos horarios de los Museos Vaticanos. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Incluida en la entrada general de los Museos Vaticanos (misma reserva).',
    price: 'Incluida en Museos Vaticanos',
    assigned_date: '2027-01-05', must_see: false,
    notes: 'No confundir el orden: primero Braccio Nuovo, después Sixtina para evitar aglomeraciones.',
    added_by: 'Precarga',
  },
  {
    name: 'Coloso de Constantino (Museos Capitolinos)', city: 'Roma', country: 'Italia',
    lat: 41.8930, lng: 12.4828, category: 'museo',
    description: 'Fragmentos colosales (cabeza, mano, esfera, brazo y pies) de la estatua acrolítica de Constantino de más de 12 m, expuestos en el patio de los Museos Capitolinos. Desde 2024 también se exhibe la reconstrucción a escala real en el jardín de Caffarelli.',
    highlights: 'Cabeza de 2,5 m con mirada hierática, mano alzada que sostuvo cetro/esfera, reconstrucción en resina a escala en el Jardín de Caffarelli.',
    opening_hours: 'Todos los días 9:30–19:30; 24 y 31 dic 9:30–14:00; 1 ene 9:30–13:30. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada combinada a los dos museos capitolinos ~€15–17 (verificar); la fila es menor que en otros museos.',
    price: '€15–17 (aprox. — verificar)',
    assigned_date: '2027-01-06', must_see: false,
    notes: 'Piazza del Campidoglio de Miguel Ángel. Combina con el Foro desde la Terrazza Tabularium.',
    added_by: 'Precarga',
  },
  {
    name: 'Foro Romano y Palatino', city: 'Roma', country: 'Italia',
    lat: 41.8925, lng: 12.4853, category: 'ruina_arqueologica',
    description: 'El corazón político, religioso y comercial de la Roma antigua durante mil años. Templos, basílicas, arcos triunfales y la Vía Sacra, con el Palatino (cuna de Roma y barrio imperial) en la colina de arriba.',
    highlights: 'Templo de Saturno, Arco de Septimio Severo, Curia Julia, Arco de Tito, Casa de las Vestales, Templo de Antonino y Faustina, vista desde el Palatino, Casa de Augusto y Livia (con reserva).',
    opening_hours: 'Todos los días 9:00–16:30/19:15 según temporada (última entrada 1h antes). Cerrado 1 ene y 25 dic. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Entrada combinada Coliseo + Foro + Palatino (~€18, válida 24h, 2 accesos al Coliseo). Reserva online recomendada ~€2. Verificar.',
    price: '€18 (combinada Coliseo — verificar)',
    assigned_date: '2027-01-06', must_see: true,
    notes: 'Entrar por Via di San Gregorio (Palatino) o Via dei Fori Imperiali. 2–3 horas. Llevar agua; poco sombra.',
    added_by: 'Precarga',
  },
  {
    name: 'Circo Máximo', city: 'Roma', country: 'Italia',
    lat: 41.8858, lng: 12.4854, category: 'ruina_arqueologica',
    description: 'El estadio más grande de la antigüedad: 621 × 118 m y aforo de ~150.000 espectadores para las carreras de cuadrigas. Hoy es un parque arqueológico al aire libre donde se aprecia el trazado de la pista y el palco imperial; entre medias subsisten restos visitables con pequeños halls.',
    highlights: 'Forma de la spina con obeliscos (el Flaminio hoy en Piazza del Popolo, el Lateranense en Piazza S. Giovanni), Torretta Valadier con vista, restos del arco de Tito.',
    opening_hours: 'Parque: siempre abierto. Sección arqueológica (torre/hall): Mar–Dom 10:00–19:00 aprox. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'El parque es gratuito; la sección expositiva tiene tarifa baja (~€5). Verificar.',
    price: 'Gratis (interior ~€5 — verificar)',
    assigned_date: '2027-01-06', must_see: false,
    notes: 'Pasa por aquí entre el Foro y las Termas de Caracalla o hacia el Aventino. 30–40 min.',
    added_by: 'Precarga',
  },
  {
    name: 'Castel Sant\'Angelo', city: 'Roma', country: 'Italia',
    lat: 41.9031, lng: 12.4663, category: 'monumento',
    description: 'Mausoleo de Adriano (siglo II) reconvertido en fortaleza papal y prisión. Conectado con el Vaticano por el Passetto di Borgo. Se recorren salas renacentistas, arsenales, la terraza con vistas 360° al Tíber y San Pedro, y hay museo con armaduras y pintura.',
    highlights: 'Terraza panorámica, Passetto (corredor de fuga de los papas), apartamentos de Julio II, loggias de Giulio Romano, patio de Alejandro VI, modelo del mausoleo original.',
    opening_hours: 'Todos los días 9:00–19:30 (última entrada 18:30); lunes 9:00–23:00 en verano. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada ~€16–17 (verificar); no suele requerir reserva anticipada, aunque hay fila corta en temporada alta.',
    price: '€16–17 (aprox. — verificar)',
    assigned_date: '2027-01-07', must_see: false,
    notes: 'Cruzando el Puente Sant\'Angelo con los ángeles de Bernini. Buena parada hacia/desde el Vaticano.',
    added_by: 'Precarga',
  },
  {
    name: 'Chiesa di Sant\'Ignazio di Loyola', city: 'Roma', country: 'Italia',
    lat: 41.8992, lng: 12.4786, category: 'iglesia',
    description: 'Iglesia jesuita barroca del siglo XVII famosa por su techo: el falso domo trompe-l\'œil de Andrea Pozzo y la gloria de San Ignacio que se funde con el cielo. Espectacular y gratis; el "dome" pintado engaña a todos.',
    highlights: 'Falso domo de Pozzo (mirar el disco amarillo del suelo), fresco de la Apoteosis de San Ignacio, espejo para ver el techo, capillas laterales.',
    opening_hours: 'Todos los días 7:30–19:00 aprox. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada libre; donativo sugerido (€1–2) para iluminación del techo.',
    price: 'Gratis',
    assigned_date: '2027-01-07', must_see: false,
    notes: 'A 2 min de la Fuente de Trevi y del Pantheón. Ir por la mañana: luz para el techo.',
    added_by: 'Precarga',
  },
  {
    name: 'Fontana di Trevi', city: 'Roma', country: 'Italia',
    lat: 41.9009, lng: 12.4833, category: 'monumento',
    description: 'La fuente barroca más famosa del mundo, terminal del acueducto Acqua Vergine. La fachada de Palazzo Poli con Océano entre caballos y tritones, restaurada por Fendi en 2015. Tradición: echar una moneda sobre el hombro derecho para volver a Roma.',
    highlights: 'Océano de Pietro Bracci, caballos calmados y agitados, monedas (~€1,5 millones/año para Caritas), acristalamiento y pasarela para el flujo de visitantes.',
    opening_hours: '24/7. Prohibido bañarse (multa ~€450). Verificar flujo/medidas antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratuita. Muy concurrida: mejor al amanecer o de noche tarde. Ultimamente con pasarela y control de acceso en horas punta.',
    price: 'Gratis',
    assigned_date: '2027-01-07', must_see: true,
    notes: 'Zona peatonal. Cuidado con los carteristas. Combinar con Pantheón, Sant\'Ignazio y Piazza Navona.',
    added_by: 'Precarga',
  },
  {
    name: 'Basilica di San Giovanni in Laterano', city: 'Roma', country: 'Italia',
    lat: 41.8859, lng: 12.5066, category: 'iglesia',
    description: 'La catedral de Roma y "madre de todas las iglesias": la basílica del obispo de Roma (el Papa), más antigua que San Pedro. Fachada de Galilei, nave con estatuas de los apóstoles, baldaquino gótico y confesión de san Pedro y san Pablo bajo el altar; Triclinio y Scala Santa enfrente.',
    highlights: 'Baldaquino gótico, tumba de Inocencio III, claustro medieval (entrada pequeña), statuas de apóstoles de Borromini, Scala Santa y Sancta Sanctorum, bautisterio octogonal.',
    opening_hours: 'Todos los días 7:00–18:30; claustro 9:00–18:00. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis. Vestimenta apropiada como en toda iglesia.',
    price: 'Gratis (claustro pequeño donativo)',
    assigned_date: '2027-01-08', must_see: false,
    notes: 'Metro A San Giovanni. Combina con Scala Santa y la Santa Croce in Gerusalemme.',
    added_by: 'Precarga',
  },
  {
    name: 'Caffetteria Italia al Vittoriano', city: 'Roma', country: 'Italia',
    lat: 41.8953, lng: 12.4823, category: 'comida',
    description: 'Cafetería en la cima del Altare della Patria (Vittoriano), con terraza panorámica sobre los Foros Imperiales y el Vittoriano. Desayuno/almuerzo con vista sin pagar mirador; acceso por el lado de la Piazza Ara Coeli.',
    highlights: 'Terraza sobre los Foros, café/croissant con vista a Piazza Venezia, acceso directo (no requiere museo).',
    opening_hours: 'Todos los días ~9:00–19:00 aprox. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Sin reserva; servicio de barra o mesa. Precios de cafetería turística.',
    price: '€ (cappuccino + cornetto ~€5–7)',
    assigned_date: '2027-01-08', must_see: false,
    notes: 'Truco para ver los Foros desde arriba gratis. Ascensor panorámico del Vittoriano aparte (~€10).',
    added_by: 'Precarga',
  },
  {
    name: 'Pompei · Sitio arqueológico', city: 'Pompeya', country: 'Italia',
    lat: 40.7497, lng: 14.4869, category: 'ruina_arqueologica',
    description: 'La ciudad romana sepultada por la erupción del Vesubio en el 79 d.C., congelada en el tiempo: calzadas, termas, villas, talleres y el anfiteatro. Patrimonio de la Humanidad; se recorren 44 de las 66 hectáreas excavadas.',
    highlights: 'Casa del Fauno, Villa de los Misterios, termas del Foro, anfiteatro, foro, tepidarium, panaderías con hornos, moldes de víctimas, encrucijada de Abundancia, té para el Vesubio.',
    opening_hours: 'Todos los días 9:00–17:00 (última entrada 15:30) en invierno; verano hasta 19:00. Cerrado 1 ene, 1 may, 25 dic. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online recomendada para evitar fila (~€19 entrada general + €2 reserva). Circumvesuviana: Napoli Centrale → Pompei Scavi (36 min). Verificar.',
    price: '€19 + €2 reserva (aprox. — verificar)',
    assigned_date: '2027-01-07', must_see: true,
    notes: 'Zapatillas cómodas, agua, gorra. 4–5 horas. Entrada por Porta Marina. Guía/audio guía recomendada. Depósito de maletas gratis en la entrada.',
    added_by: 'Precarga',
  },

  // ───────────────────────── FLORENCIA ─────────────────────────
  {
    name: 'Cattedrale di Santa Maria del Fiore (Duomo)', city: 'Florencia', country: 'Italia',
    lat: 43.7731, lng: 11.2560, category: 'iglesia',
    description: 'La catedral gótico-renacentista de Florencia con la cúpula de Brunelleschi, obra maestra de la ingeniería del Quattrocento. El complejo incluye baptisterio, campanile de Giotto, cripta y museo (Bigallo).',
    highlights: 'Cúpula de Brunelleschi (subida con reserva, 463 escalones), fachada de mármol, puertas del Paraíso del baptisterio (copia), frescos de la cúpula (Zuccari/Vasari), cripta de Santa Reparata.',
    opening_hours: 'Catedral Lun–Sáb 10:15–15:30 (domingos cerrada al culto turístico). Cúpula y baptisterio: horarios aparte. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'La subida a la cúpula SOLO con reserva de franja (se agota días antes) en ilduomo.firenze.it. Entrada combinada Brunelleschi Pass ~€30. Verificar.',
    price: '€30 (Brunelleschi Pass — verificar)',
    assigned_date: '2027-01-04', must_see: true,
    notes: 'Reservar la cúpula con mucha antelación; sin maletas ni bolsos grandes. Campanile alternativa si se agota.',
    added_by: 'Precarga',
  },
  {
    name: 'Galleria dell\'Accademia (David de Miguel Ángel)', city: 'Florencia', country: 'Italia',
    lat: 43.7762, lng: 11.2581, category: 'museo',
    description: 'Museo centrado en el David de Miguel Ángel (1504) y otras esculturas suyas, más la colección de tablas góticas y los instrumentos musicales del Conservatorio. Sala original donde David mira a Roma.',
    highlights: 'David (5,17 m), Prisioneros (esclavos inacabados) de Miguel Ángel, San Mateo, colección de instrumentos antiguos, tablas de Orcagna.',
    opening_hours: 'Mar–Dom 8:15–18:50; lunes cerrado. Última entrada 18:20. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online recomendada (franjas de 15 min, se agota en temporada). Entrada ~€16 + reserva €4. Verificar.',
    price: '€16 + €4 reserva (aprox. — verificar)',
    assigned_date: '2027-01-04', must_see: true,
    notes: '1–1,5 h. Ir temprano o última hora. Cerca de San Marco y del Mercato Centrale.',
    added_by: 'Precarga',
  },
  {
    name: 'Galleria degli Uffizi', city: 'Florencia', country: 'Italia',
    lat: 43.7678, lng: 11.2552, category: 'museo',
    description: 'La gran pinacoteca de los Medici en el edificio de oficinas de Cosimo I: el mejor recorrido del Renacimiento italiano, del Gótico al Barroco. La loggia superior da al Arno y al Ponte Vecchio.',
    highlights: 'El Nacimiento de Venus y La Primavera de Botticelli, Anunciación de Leonardo, Doni Tondo de Miguel Ángel, Venus de Urbino de Tiziano, Caravaggio (Baco), Medusa de Caravaggio, sala de mapas.',
    opening_hours: 'Mar–Dom 8:15–18:30; lunes cerrado. Última entrada 17:30. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva de franja online obligatoria en temporada (~€25 + €4 reserva). Pase combinado Uffizi+Accademia disponible. Verificar.',
    price: '€25 + €4 reserva (aprox. — verificar)',
    assigned_date: '2027-01-04', must_see: true,
    notes: '2,5–3 h. Reservar con semanas de antelación. Entrada por la loggia del lado del Arno.',
    added_by: 'Precarga',
  },
  {
    name: 'Ponte Vecchio', city: 'Florencia', country: 'Italia',
    lat: 43.7679, lng: 11.2531, category: 'monumento',
    description: 'El puente medieval sobre el Arno (1345) cubierto de orfebres desde el siglo XVI; sobrevivió intacto a la Segunda Guerra Mundial. Encima pasa el Corredor Vasariano que unía el Palazzo Vecchio con los Pitti.',
    highlights: 'Tiendas de joyería, busto de Benvenuto Cellini, vista del Corredor Vasariano, atardecer sobre el Arno, vista desde el Ponte Santa Trinita vecino.',
    opening_hours: 'Siempre abierto (pasarela peatonal).',
    reservation_required: false,
    reservation_notes: 'Gratis cruzarlo. El Corredor Vasariano se visita solo con tour y reserva anticipada.',
    price: 'Gratis',
    assigned_date: '2027-01-04', must_see: false,
    notes: 'Atardecer mágico. Cuidado con los carteristas en la aglomeración.',
    added_by: 'Precarga',
  },
  {
    name: 'Piazzale Michelangelo', city: 'Florencia', country: 'Italia',
    lat: 43.7623, lng: 11.2646, category: 'paseo_barrio',
    description: 'La terraza panorámica del siglo XIX sobre Florencia: vista de postal del Duomo, Palazzo Vecchio, el Arno y las colinas de Fiesole. Copia en bronce del David en el centro; al lado, la iglesia románica de San Miniato al Monte.',
    highlights: 'Panorama 180°, David de bronce, escalinata, San Miniato al Monte y su cementerio, atardeceres legendarios.',
    opening_hours: 'Siempre abierto (es una plaza).',
    reservation_required: false,
    reservation_notes: 'Gratis. Se sube a pie por las Rambe (20 min) o bus 12/13.',
    price: 'Gratis',
    assigned_date: '2027-01-04', must_see: false,
    notes: 'Ir al atardecer; después bajar a cenar a San Niccolò. Noche con frío en enero.',
    added_by: 'Precarga',
  },

  // ───────────────────────── VENECIA ─────────────────────────
  {
    name: 'Basilica di San Marco', city: 'Venecia', country: 'Italia',
    lat: 45.4345, lng: 12.3388, category: 'iglesia',
    description: 'La basílica dorada de Venecia: arte bizantino del siglo XI con 8.000 m² de mosaicos, Pala d\'Oro, tesoros saqueados a Constantinopla y los cuatro caballos de bronce en la loggia. Unica en su género fuera de Estambul.',
    highlights: 'Mosaicos de la cúpula de la Ascensión, Pala d\'Oro (esmaltes bizantinos), Caballos de San Marcos, tumba de San Marcos, Museo della Basilica y loggia con vista a la plaza, Tesoro.',
    opening_hours: 'Basílica Lun–Sáb 9:45–17:00, Dom y festivos 14:00–17:00 (horarios religiosos aparte). Museo y Pala: horarios propios. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Entrada basílica €3 + reserva online €3 (evita la fila de hasta 1h). Pala d\'Oro €5, museo €7, tesoro €5. Verificar.',
    price: '€3 + extras (verificar)',
    assigned_date: '2027-01-03', must_see: true,
    notes: 'Vestimenta apropiada. No se puede entrar con maletas. La loggia y los caballos: vista perfecta de la Piazza.',
    added_by: 'Precarga',
  },
  {
    name: 'Palazzo Ducale', city: 'Venecia', country: 'Italia',
    lat: 45.4348, lng: 12.3396, category: 'museo',
    description: 'El palacio de los dux: gótico veneciano con los Salones del Consejo decorados por Tintoretto y Veronés, salas de justicia, prisiones y el Puente de los Suspiros cruzando al lado penitenciario. Centro político de la Serenísima durante mil años.',
    highlights: 'Sala del Maggior Consiglio (Paraíso de Tintoretto), Sala dello Scrutinio, Escalera de Oro, Ponte dei Sospiri (interior), armería, cármenes (Pozzi), loggia con vista a la laguna.',
    opening_hours: 'Todos los días 9:00–18:00 (verano hasta 19:00; última entrada 1h antes). Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Entrada estándar ~€30 con reserva online recomendada. El "Secret Itineraries" tour requiere reserva aparte. Verificar.',
    price: '€30 (aprox. — verificar)',
    assigned_date: '2027-01-03', must_see: true,
    notes: '2 h. Combinar con la Basilica (frente). El tour de los itinerarios secretos, si hay tiempo.',
    added_by: 'Precarga',
  },
  {
    name: 'Canal Grande en vaporetto (línea 1)', city: 'Venecia', country: 'Italia',
    lat: 45.4380, lng: 12.3358, category: 'paseo_barrio',
    description: 'Recorrido en vaporetto por la "S" del Gran Canal, la avenida acuática flanqueada por palacios del Renacimiento: de Piazzale Roma a San Marco, pasando por Rialto, el Puente de la Academia y la Salute.',
    highlights: 'Palacios (Ca\' d\'Oro, Ca\' Rezzonico, Palazzo Grassi), Puente de Rialto, Punta della Dogana, Santa Maria della Salute, giao del ferrocarril.',
    opening_hours: 'Línea 1: cada 12 min aprox, 5:00–23:30. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Billete único de vaporetto ~€9,50 (75 min) o pase ACTV 24h/72h (~€25/€35). Verificar tarifas.',
    price: '€9,50 viaje (pases disponibles)',
    assigned_date: '2027-01-03', must_see: false,
    notes: 'Subir en la proa del vaporetto. Traghetto en Rialto como alternativa económica (~€2).',
    added_by: 'Precarga',
  },
  {
    name: 'Burano', city: 'Venecia', country: 'Italia',
    lat: 45.4856, lng: 12.4167, category: 'paseo_barrio',
    description: 'Isla de la laguna famosa por sus casas de colores intensos, el encaje de bolillos y la inclinada torre campanile. Colores regulados por decreto; el ambiente de pesca y encaje es único.',
    highlights: 'Casas multicolores (la casa de Bepi Suà), torre inclinada de San Martino, Museo del Merletto, pescado fresco en trattorias, canal principal.',
    opening_hours: 'Siempre accesible (vaporetto línea 12 desde Fondamente Nove, ~42 min).',
    reservation_required: false,
    reservation_notes: 'Requiere billete de vaporetto (pase ACTV). Sin entrada alguna.',
    price: 'Transporte vaporetto',
    assigned_date: '2027-01-03', must_see: false,
    notes: 'Medio día. Combinar con Murano (vidrio) si hay tiempo. Soleado preferible para las fotos.',
    added_by: 'Precarga',
  },

  // ───────────────────────── VERONA ─────────────────────────
  {
    name: 'Arena di Verona', city: 'Verona', country: 'Italia',
    lat: 45.4392, lng: 10.9299, category: 'ruina_arqueologica',
    description: 'El anfiteatro romano mejor conservado del mundo (siglo I d.C.), tercer mayor tras Coliseo y Capua: 30.000 espectadores, aún activo para la ópera. Se recorre el anillo exterior y la cavea.',
    highlights: 'Anillo exterior de 4 anillos (sobreviven 2), cavea intacta, acústica legendaria, opera festival de verano, vista desde la colina Castel San Pietro.',
    opening_hours: 'Todos los días 8:30–19:30 (última entrada 18:30); horario reducido en días de montaje de ópera. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada ~€12–14 (verificar); sin reserva suele bastar en enero.',
    price: '€12–14 (aprox. — verificar)',
    assigned_date: '2027-01-02', must_see: true,
    notes: 'Pausa perfecta del tren Milán→Venecia. Piazza Bra al lado, con cafeterías. Casco histórico de Verona a 10 min a pie (Casa di Giulietta, Piazza delle Erbe).',
    added_by: 'Precarga',
  },

  // ───────────────────────── MILÁN ─────────────────────────
  {
    name: 'Arco della Pace', city: 'Milán', country: 'Italia',
    lat: 45.4742, lng: 9.1717, category: 'monumento',
    description: 'Arco triunfal neoclásico (siglo XIX) en la puerta del Parco Sempione, coronado con la cuadriga de la Paz. Iniciado bajo Napoleón y terminado por los austriacos; encabeza el eje del Corso Sempione.',
    highlights: 'Cuadriga de bronce, relieves de la caída de Napoleón, vista desde el Sempione, cafés y aperitivo en Corso Sempione, atardecer con la Torre Branca.',
    opening_hours: 'Siempre accesible (monumento urbano en plaza abierta).',
    reservation_required: false,
    reservation_notes: 'Gratis. Zona de aperitivo muy animada.',
    price: 'Gratis',
    assigned_date: '2027-01-02', must_see: false,
    notes: 'Combinar con el Parco Sempione, Castello Sforzesco y Torre Branca. Metro: Moscova o Lanza.',
    added_by: 'Precarga',
  },

  // ───────────────────────── PARÍS ─────────────────────────
  {
    name: 'Torre Eiffel', city: 'París', country: 'Francia',
    lat: 48.8584, lng: 2.2945, category: 'monumento',
    description: 'El icono de hierro de 330 m construido por Gustave Eiffel para la Exposición Universal de 1889. Tres plantas visitables: primera con suelo de cristal, segunda con vista óptima, cumbre panorámica; el brillo de 20.000 bombillas cada hora al anochecer.',
    highlights: 'Cumbre (elevador+ascensor), suelo de cristal de la 1ª planta, restaurante Le Jules Verne, parpadeo dorado cada hora por la noche (5 min), Champ de Mars al pie.',
    opening_hours: 'Todos los días 9:00–0:45 (última cumbre 22:30); escalera hasta las 18:30. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online de franja MUY recomendada (se agota con semanas). Ascensor hasta cumbre ~€29, hasta 2ª planta ~€18, escalera ~€11. Verificar.',
    price: '€18–29 (aprox. — verificar)',
    assigned_date: '2026-12-28', must_see: true,
    notes: 'Reservar con 60 días de antelación exacta (apertura de ventas). Mejor vista gratuita: Trocadéro al amanecer.',
    added_by: 'Precarga',
  },
  {
    name: 'Museo del Louvre', city: 'París', country: 'Francia',
    lat: 48.8606, lng: 2.3376, category: 'museo',
    description: 'El museo más visitado del mundo: antiguo palacio real con la pirámide de I. M. Pei y 35.000 obras, desde Antigüedades orientales y egipcias hasta pintura francesa, italiana y flamenca.',
    highlights: 'Mona Lisa, Venus de Milo, Victoria de Samotracia, Las bodas de Caná, Códice de Hammurabi, Psique reanimada, Coro de las Sibilas, sección egipcia.',
    opening_hours: 'Lun, Mié, Jue, Vie, Sáb, Dom 9:00–18:00; viernes hasta 21:45; martes cerrado. Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online de franja OBLIGATORIA (sin ticket no hay cola física). ~€22. Verificar.',
    price: '€22 (aprox. — verificar)',
    assigned_date: '2026-12-29', must_see: true,
    notes: 'Entrada por Carrousel (menos fila). 3 h mínimas. Planificar ruta previa: Denon (Mona Lisa) se satura.',
    added_by: 'Precarga',
  },
  {
    name: 'Palacio de Versalles', city: 'Versalles', country: 'Francia',
    lat: 48.8049, lng: 2.1204, category: 'monumento',
    description: 'El palacio de Luis XIV: 2.300 habitaciones, Galería de los Espejos, jardines formales de Le Nôtre con fuentes y el Grand Trianon. Símbolo de la monarquía absoluta y Patrimonio de la Humanidad.',
    highlights: 'Galería de los Espejos, apartamentos del Rey y la Reina, capilla real, jardines y fuentes musicales, Grand Trianon, Hameau de la Reina (María Antonieta), sala de coronaciones.',
    opening_hours: 'Palacio 9:00–18:30 (cerrado lunes); jardines todos los días 8:00–18:30 (fuentes musicales según calendario). Verificar antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Reserva online de franja obligatoria para el Palacio (~€21 con jardines; pase Passport ~€32). Tren RER C desde París (40 min). Verificar.',
    price: '€21–32 (aprox. — verificar)',
    assigned_date: '2026-12-30', must_see: true,
    notes: 'Día completo. Llevar abrigo: los jardines en invierno son fríos. Entrar temprano por la puerta B.',
    added_by: 'Precarga',
  },
  {
    name: 'Arco del Triunfo', city: 'París', country: 'Francia',
    lat: 48.8738, lng: 2.2950, category: 'monumento',
    description: 'El arco triunfal más grande del mundo (50 m), ordenado por Napoleón tras Austerlitz. Bajo su bóveda descansa la Tumba del Soldado Desconocido con la llama reavivada cada noche. Terraza con vista de los 12 bulevares que irradian de l\'Étoile.',
    highlights: 'Terraza panorámica (284 escalones o ascensor), relieves de La Marsellesa, Tumba del Soldado Desconocido, vista del eje Champs-Élysées–La Défense.',
    opening_hours: 'Todos los días 10:00–22:30 (23:00 en verano). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada terraza ~€13–16 (verificar); gratis con Paris Museum Pass. Subir por el paso subterráneo (¡no cruzar la rotonda!).',
    price: '€13–16 (aprox. — verificar)',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Combinar con Champs-Élysées a pie. Vista nocturna de la Torre Eiffel parpadeante.',
    added_by: 'Precarga',
  },
  {
    name: 'Tumba de Napoleón (Les Invalides)', city: 'París', country: 'Francia',
    lat: 48.8568, lng: 2.3123, category: 'monumento',
    description: 'El Dôme de los Inválidos, con su cúpula dorada, custodia el sarcófago de cuarcita roja de Napoleón Bonaparte, rodeado de sus hermanos y mariscales. Alberga también el Museo del Ejército.',
    highlights: 'Sarcófago de Napoleón en pórfido, cripta con columnas, cúpula dorada (560.000 panes de oro), Museo del Ejército (armaduras, canones, uniforms), Hugo de Windsor en la sala de mapas.',
    opening_hours: 'Todos los días 10:00–18:00 (verano hasta 21:00); 1 ene, 1 may, 1 nov, 25 dic cerrado. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada ~€15 (verificar); gratis con Paris Museum Pass. Sin reserva obligatoria.',
    price: '€15 (aprox. — verificar)',
    assigned_date: '2026-12-31', must_see: false,
    notes: '2 h. Vista de la cúpula desde la esplanada gratis. Cerca: Rodin Museum y Rue Cler.',
    added_by: 'Precarga',
  },
  {
    name: 'La Sorbona', city: 'París', country: 'Francia',
    lat: 48.8490, lng: 2.3435, category: 'monumento',
    description: 'La universidad más antigua de Francia (1257), corazón del Barrio Latino. El anfiteatro y la capilla del siglo XVII se visitan con visita guiada; el exterior en la Place de la Sorbonne es icónico.',
    highlights: 'Grand Amphithéâtre (visita guiada), capilla de Sorbona, Place de la Sorbonne, biblioteca, barrio latino con librerías (Shakespeare and Company a 10 min).',
    opening_hours: 'Visita guiada solo con reserva (sábados, 1h). Verificar disponibilidad antes del viaje.',
    reservation_required: true,
    reservation_notes: 'Visita guiada oficial con reserva online (~€12–15, sábados). Sin guía no se accede a interiores. Verificar.',
    price: '€12–15 (visita guiada — verificar)',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Si no hay visitas disponibles, pasear el Barrio Latino y la Place de la Sorbonne es suficiente.',
    added_by: 'Precarga',
  },
  {
    name: 'La Bastilla (Place de la Bastille)', city: 'París', country: 'Francia',
    lat: 48.8532, lng: 2.3692, category: 'monumento',
    description: 'La plaza donde se alzaba la fortaleza-prisión tomada el 14 de julio de 1789, inicio de la Revolución. Hoy la Colonne de Juillet corona el punto; quedan cimientos de la Bastilla en la estación de metro.',
    highlights: 'Colonne de Juillet (Genio de la Libertad), cimientos visibles en el andén 5 del metro (línea 5), Ópera Bastille, Port de l\'Arsenal y Canal Saint-Martin al lado.',
    opening_hours: 'Siempre accesible (plaza pública). Metro-cimientos en horario de servicio.',
    reservation_required: false,
    reservation_notes: 'Gratis. Pasear el Port de l\'Arsenal y Marché d\'Aligre cerca.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Combinar con Marais y Canal Saint-Martin. Ópera Bastille con visitas guiadas si interesa.',
    added_by: 'Precarga',
  },
  {
    name: 'Catedral de Notre-Dame', city: 'París', country: 'Francia',
    lat: 48.8530, lng: 2.3499, category: 'iglesia',
    description: 'La catedral gótica más famosa del mundo, reabierta en diciembre de 2024 tras el incendio de 2019. Interior restaurado con luminosidad espectacular, rosetones del siglo XIII, y la nave más alta de las catedrales góticas tempranas.',
    highlights: 'Rosetones norte y sur, coro restaurado, órgano Cavaillé-Coll, tesoro reabierto, cripta arqueológica (Ile de la Cité), parvis renovado, torre-campanario (reserva aparte).',
    opening_hours: 'Todos los días 7:45–19:00 (jueves hasta 22:00). Visita libre; torres con reserva. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Entrada gratuita; fila de seguridad. Torres con reserva online aparte (~€16). Verificar.',
    price: 'Gratis (torres ~€16 — verificar)',
    assigned_date: '2026-12-29', must_see: true,
    notes: 'Ir temprano o después de las 17h. La plaza y el exterior valen la pena incluso con fila larga.',
    added_by: 'Precarga',
  },
  {
    name: 'Église Saint-Sulpice', city: 'París', country: 'Francia',
    lat: 48.8510, lng: 2.3336, category: 'iglesia',
    description: 'La segunda iglesia más grande de París, tras Notre-Dame: clasicista del siglo XVII, con las dos torres desiguales, murales de Delacroix en la capilla de los Ángeles y el gnómon astronómico en el suelo.',
    highlights: 'Capilla de los Ángeles (Delacroix: Jacob y el ángel), gnómon con línea de meridiano, órgano Cavaillé-Coll monumental, torres de Servandoni, fuente de los cuatro obispos frente a la iglesia.',
    opening_hours: 'Todos los días 7:30–19:30. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Cerca del Jardin du Luxembourg. Fama añadida por El código Da Vinci.',
    added_by: 'Precarga',
  },
  {
    name: 'Église Saint-Eustache', city: 'París', country: 'Francia',
    lat: 48.8662, lng: 2.3469, category: 'iglesia',
    description: 'Iglesia gótica renacentista en Les Halles: nave de 105 m con proporciones catedralicias, órganos legendarios y el tríptico de Thomas Couture. Bautizaron a Molière y Richelieu; el "Cabeza Grande" de/kernel de Huang Yong Ping protege la entrada.',
    highlights: 'Órgano de 8.000 tubos, Cabeza Grande de Huang Yong Ping, tríptico de Couture, vitrales contemporáneos, capilla de la Virgen.',
    opening_hours: 'Lun–Sáb 9:30–19:00, Dom 9:00–19:00. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis. Conciertos de órgano algunos domingos.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'A 5 min del Louvre y del Centre Pompidou. Ideal al pasar por Les Halles.',
    added_by: 'Precarga',
  },
  {
    name: 'La Madeleine', city: 'París', country: 'Francia',
    lat: 48.8701, lng: 2.3245, category: 'iglesia',
    description: 'Iglesia con forma de templo griego (52 columnas corintias) en el eje Concorde–Assemblée: construida como granero de honor napoleónico y terminada como iglesia de María Magdalena. Interior con cúpula y frescos.',
    highlights: 'Frontón del Juicio Final, cúpula interior con mosaicos, altar de Charles Marochetti, órganos, vista del eje hasta la Place de la Concorde.',
    opening_hours: 'Todos los días 9:30–19:00. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Cerca de la Place de la Concorde y las tiendas de la Rue Royale.',
    added_by: 'Precarga',
  },
  {
    name: 'Musée d\'Art Moderne de Paris', city: 'París', country: 'Francia',
    lat: 48.8636, lng: 2.3020, category: 'museo',
    description: 'Museo municipal en el ala este del Palais de Tokyo, con una de las mejores colecciones de arte moderno y contemporáneo de París: Fauvismo, Dada, Escuela de París, Raoul Dufy (La Fée Électricité, el cuadro más grande del mundo).',
    highlights: 'La Fée Électricité de Dufy, Matisse (La Danza in situ), Derain, Picasso, Modigliani, sala de Dada, terraza con vista a la Torre Eiffel.',
    opening_hours: 'Mar–Dom 10:00–18:00; jueves hasta 21:45 (expos temporales); lunes cerrado. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Colección permanente GRATUITA; exposiciones temporales de pago (~€12–15). Verificar.',
    price: 'Gratis (permanente)',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Muy subestimado y sin colas. Terraza del Palais de Tokyo con la Torre Eiffel de fondo.',
    added_by: 'Precarga',
  },
  {
    name: 'Musée Fragonard (Maison Alphand)', city: 'París', country: 'Francia',
    lat: 48.8780, lng: 2.3110, category: 'museo',
    description: 'El museo de la casa de perfumes Fragonard: petit hotel del siglo XIX cerca de la Ópera con colección de perfumería, frascos antiguos, alambiques y visitas guiadas gratuitas con muestra. Tienda adjunta.',
    highlights: 'Visita guiada gratuita (~30 min), colección de perfumes del siglo XVIII–XX, alambique de cobre, tienda con descuento.',
    opening_hours: 'Lun–Sáb 9:00–18:00. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis. Visita guiada en varios idiomas a horas fijas (consultar).',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Parada breve y agradecida cerca de la Ópera Garnier. Comprar souvenirs aquí.',
    added_by: 'Precarga',
  },
  {
    name: 'Jardin du Luxembourg', city: 'París', country: 'Francia',
    lat: 48.8462, lng: 2.3372, category: 'parque',
    description: 'El jardín del Senado y del Palais de Luxemburgo (María de Médici, 1612): parterre francés, estanque central con veleros para niños, estatuas de reinas de Francia, palmeras transportadas en invierno.',
    highlights: 'Grand Bassin con veleros, Medici Fountain, Palais du Luxembourg, estatuas de reinas, quiosco de helados, terraza de juegos infantiles, vista del Panteón.',
    opening_hours: 'Todos los días según luz natural: ~7:30–anochecer. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Cafés alrededor: Rue de Seine, Rue de Buci. Combina con Saint-Sulpice y Saint-Germain.',
    added_by: 'Precarga',
  },
  {
    name: 'Jardin des Tuileries', city: 'París', country: 'Francia',
    lat: 48.8635, lng: 2.3275, category: 'parque',
    description: 'El jardín francés más clásico de París, entre el Louvre y la Place de la Concorde: estanques octogonales, esculturas de Maillol y Giacometti, macizos de flores y el Musée de l\'Orangerie en un extremo.',
    highlights: 'Grand Bassin Rond, Orangerie (Nenúfares de Monet, entrada aparte), Jeu de Paume, esculturas al aire libre, vista del eje histórico Concorde–Arco.',
    opening_hours: 'Todos los días ~7:00–19:30 (invierno 7:30–19:00). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Paseo obligatorio entre Louvre y Concorde. Sillas verdes junto al estanque: paisaje parisino.',
    added_by: 'Precarga',
  },
  {
    name: 'Parc des Buttes-Chaumont', city: 'París', country: 'Francia',
    lat: 48.8806, lng: 2.3820, category: 'parque',
    description: 'El parque romántico más dramático de París (1867): acantilados, cascada artificial, lago interior, grotto con estalactitas y el templo de la Sibila en lo alto de la île du Belvédère. Los puentes colgantes y la vista de Montmartre rematan el conjunto.',
    highlights: 'Temple de la Sibylle, puente colgante de 64 m, cascada y grotto, viaducto para trenes, vistas 360° desde el templo, zonas de picnic.',
    opening_hours: 'Todos los días ~7:00–21:00 (invierno 7:00–anochecer). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Menos turístico y muy local. Cerca: Canal Saint-Martin y el barrio de Belleville.',
    added_by: 'Precarga',
  },
  {
    name: 'Parc Monceau', city: 'París', country: 'Francia',
    lat: 48.8797, lng: 2.3095, category: 'parque',
    description: 'Jardín anglo-chino del siglo XVIII con caprichos arquitectónicos: pirámide, columnata de corinto remanente del Hôtel de Salm, puente egipcio, estanque con colonnada. Rodeado de hoteles particulares y a puertas de la Ópera.',
    highlights: 'Columnata corintia, pirámide, puente egipcio, estatua de Chopin, entrada con verja dorada, mansión alrededor.',
    opening_hours: '~7:00–22:00 (verano). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Barrio elegante para pasear: Parc Monceau → Musée Nissim de Camondo → arcadas de la Rue de Rivoli.',
    added_by: 'Precarga',
  },
  {
    name: 'Parc de la Villette', city: 'París', country: 'Francia',
    lat: 48.8902, lng: 2.3895, category: 'parque',
    description: 'El parque más vanguardista de París (Bernard Tschumi, 1987): follies rojas geometricales, jardines temáticos, Cité des Sciences y la Géode, el Zénith y la Philharmonie. Ciclovía y canal lindando con Pantin.',
    highlights: 'Follies rojas (26), jardines del Dragon y del Viento, Cité des Sciences (científico), La Géode (espejo), canal de Ourcq, cine al aire libre en verano.',
    opening_hours: 'Siempre accesible (parque urbano). Museos del parque con horarios propios.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Lejos del centro: ir si hay tiempo o interés por arquitectura contemporánea.',
    added_by: 'Precarga',
  },
  {
    name: 'Promenade Plantée (Coulée Verte)', city: 'París', country: 'Francia',
    lat: 48.8478, lng: 2.3880, category: 'parque',
    description: 'El viaducto ferroviario abandonado convertido en jardín elevado (1988-1994): 4,5 km de paseo arbolado sobre la Avenue Daumesnil, desde la Bastilla hasta el Bois de Vincennes. El original que inspiró la High Line de Nueva York.',
    highlights: 'Viaduc des Arts con talleres debajo, rosaleda, bambúes, pasos elevados, vistas de azoteas, acceso por escaleras en varias bocas.',
    opening_hours: 'Todos los días ~7:00–21:30 (invierno hasta anochecer). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Entrar por la escalera de la Avenue Daumesnil (cerca Bastilla). Pasear primero el Viaduc des Arts.',
    added_by: 'Precarga',
  },
  {
    name: 'Bois de Boulogne', city: 'París', country: 'Francia',
    lat: 48.8642, lng: 2.2485, category: 'parque',
    description: 'El gran bosque-oeste de París (846 ha, el doble de Central Park): lagos con barcas, jardines (Bagatelle, serres d\'Auteuil), hipódromos, el Stade Roland Garros y el Fondation Louis Vuitton de Gehry.',
    highlights: 'Jardin de Bagatelle (rosales, pavos reales), Fondation Louis Vuitton, Lac Inférieur con barcas, serres d\'Auteuil (invernaderos), el hippódromo de Longchamp.',
    opening_hours: 'Siempre accesible (carreteras y senderos); jardines con horario propio.',
    reservation_required: false,
    reservation_notes: 'Gratis (jardines y museos aparte). No entrar de noche en zonas apartadas.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Fondation Louis Vuitton merece reserva aparte. Metro Les Sablons o Porte Maillot.',
    added_by: 'Precarga',
  },
  {
    name: 'Puente Alexandre III', city: 'París', country: 'Francia',
    lat: 48.8639, lng: 2.3131, category: 'monumento',
    description: 'El puente más ornamentado de París (1900): arcada de acero con ángeles, ninfas y caballos alados, faroles Art Nouveau, y vista del eje Invalides–Grand Palais. Regalo de la alianza franco-rusa.',
    highlights: 'Caballos alados (Pegasos), ninfas de la Sena y del Neva, faroles Art Nouveau, vista de la Torre Eiffel hacia el oeste, Grand Palais y Petit Palais a un lado.',
    opening_hours: 'Siempre accesible.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-30', must_see: false,
    notes: 'Fotografía clásica al atardecer con la Torre Eiffel enmarcada. Petit Palais (gratis) al lado.',
    added_by: 'Precarga',
  },
  {
    name: 'Pont des Arts', city: 'París', country: 'Francia',
    lat: 48.8583, lng: 2.3375, category: 'monumento',
    description: 'El puente peatonal metálico (1804) que cruza el Sena del Institut de France al Louvre: la sala de estar de París, con músicos, pintores y las mejores vistas al Palais de la Cité y el Institut.',
    highlights: 'Vista frontal de Notre-Dame y la Sainte-Chapelle, bancos de madera, artistas callejeros, atardecer sobre el Sena, paseo en barco (bateaux) debajo.',
    opening_hours: 'Siempre accesible.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'El lugar clásico para sentarse con un crepe o un vino (prohibido el candado desde 2015).',
    added_by: 'Precarga',
  },
  {
    name: 'Rue Crémieux', city: 'París', country: 'Francia',
    lat: 48.8476, lng: 2.3690, category: 'paseo_barrio',
    description: 'Callejón peatonal del siglo XIX cerca de la Gare de Lyon: casitas adosadas de colores pastel con nombres poéticos pintados en las fachadas. La "Portofino de París" para fotos.',
    highlights: 'Fachadas rosa, azul y verde, nombres de las casas pintados, adoquines, plantas.',
    opening_hours: 'Siempre accesible (peatonal).',
    reservation_required: false,
    reservation_notes: 'Gratis. Respetar a los vecinos: es residencial.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: '10–15 min de parada fotográfica. Cerca: Gare de Lyon y Coulée Verte.',
    added_by: 'Precarga',
  },
  {
    name: 'Cour Napoléon (patio del Louvre)', city: 'París', country: 'Francia',
    lat: 48.8611, lng: 2.3364, category: 'monumento',
    description: 'El gran patio del Louvre con la pirámide de vidrio de I. M. Pei (1989) en el centro, flanqueada por las alas Richelieu, Denon y Sully, el Arco de Triunfo del Carrousel y los jardines de las Tuileries.',
    highlights: 'Pirámide de vidrio (673 rombos), pirámide invertida del Carrousel, Arco del Carrousel, vista nocturna iluminada, jardines de la Infanta.',
    opening_hours: 'Siempre accesible (patio público).',
    reservation_required: false,
    reservation_notes: 'Gratis. La pirámide de noche es un clásico.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Foto nocturna obligatoria. No confundir con la entrada al museo (requiere reserva).',
    added_by: 'Precarga',
  },
  {
    name: 'Palais-Royal', city: 'París', country: 'Francia',
    lat: 48.8637, lng: 2.3370, category: 'paseo_barrio',
    description: 'Palacio con jardín público y arcadas del siglo XVIII junto al Louvre: las Columnas de Buren (rayas blancas y negras) en el patio, las boutiques de las Galeries de Valois y los jardines con rosales y bancos.',
    highlights: 'Colonnes de Buren (Les Deux Plateaux), jardín tranquilo con fuentes, Galerie de Valois y de Montpensier, Comédie-Française, sculptural Fontaine Molière cerca.',
    opening_hours: 'Jardín ~7:30–anochecer; arcadas en horario comercial.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Oasis de silencio a 3 min del Louvre. Foto con las columnas de Buren imprescindible.',
    added_by: 'Precarga',
  },
  {
    name: 'Hôtel de Ville', city: 'París', country: 'Francia',
    lat: 48.8566, lng: 2.3522, category: 'monumento',
    description: 'El ayuntamiento de París, palacio renacentista reconstruido por Haussmann en el siglo XIX sobre el original de 1533. Fachada con 108 estatuas de parisinos ilustres; la plaza de delante se convierte en pista de hielo en invierno.',
    highlights: 'Fachada flamenca con estatuas, Plaza de Grève (pista de hielo invernal), salas de recepción (visitas guiadas con reserva), historia de la liberación de París.',
    opening_hours: 'Exterior siempre; visitas guiadas con reserva (sábados). Pista de hielo en invierno (dic–mar). Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Exterior y plaza gratis. La pista de hielo es gratuita con patines propios (alquiler aparte).',
    price: 'Gratis (exterior)',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Si coincide con la pista de hielo invernal, patinar con vistas al Sena. Cerca: Marais y Pont d\'Arcole.',
    added_by: 'Precarga',
  },
  {
    name: 'Place de la Concorde', city: 'París', country: 'Francia',
    lat: 48.8656, lng: 2.3211, category: 'monumento',
    description: 'La plaza mayor de París (86.400 m²), donde se guillotinó a Luis XVI: obelisco de Luxor de 3.300 años, dos fuentes, estatuas de las ciudades francesas y el eje histórico Champs-Élysées–Louvre–Arco del Triunfo–La Défense.',
    highlights: 'Obelisco de Luxor ( hieroglyphics reales), Fontaine des Mers y des Fleuves, Hôtel Crillon, vista del Arco del Triunfo desde el eje, statuas de ciudades.',
    opening_hours: 'Siempre accesible (plaza pública).',
    reservation_required: false,
    reservation_notes: 'Gratis. Cuidado con el tráfico al cruzar.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Paso natural entre Madeleine, Tuileries y los Campos Elíseos. La rueda de la fortuna en fiestas.',
    added_by: 'Precarga',
  },
  {
    name: 'Canal Saint-Martin', city: 'París', country: 'Francia',
    lat: 48.8709, lng: 2.3661, category: 'paseo_barrio',
    description: 'El canal (1825) con esclusas y puentes giratorios que une el Bassin de la Villette con el Sena: orillas donde parisienses jóvenes hacen picnic, boutiques vintage, cafés especializados y el Hôtel du Nord de la película.',
    highlights: 'Esclusas y puentes giratorios, Bassin de la Villemin, Quai de Valmy, cafés (Le Comptoir Général), tiendas vintage, cruceros cortos por las esclusas.',
    opening_hours: 'Orillas siempre accesibles.',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Caminar de la Bastilla a la Villette (~40 min). Desvíos: Rue Beaurepaire y Rue des Vinaigriers.',
    added_by: 'Precarga',
  },
  {
    name: 'Barrio Latino', city: 'París', country: 'Francia',
    lat: 48.8470, lng: 2.3430, category: 'paseo_barrio',
    description: 'El barrio universitario desde la Edad Media: Sorbona, librerías, cafés históricos (Les Deux Magots, Café de Flore), el Panteón, las termas de Cluny y las estrechas Rue de la Huchette y Mouffetard.',
    highlights: 'Panteón (tumbas de Voltaire, Hugo, Curie), Shakespeare and Company, Rue Mouffetard, Jardines del Luxemburgo al borde, Arenas de Lutecia, Musée de Cluny.',
    opening_hours: 'Siempre accesible (barrio).',
    reservation_required: false,
    reservation_notes: 'Gratis pasear; museos y Panteón con entrada.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Cena en Rue Mouffetard o Rue Saint-Jacques. Crepes en la Rue de la Huchette (turístico pero clásico).',
    added_by: 'Precarga',
  },
  {
    name: 'Shakespeare and Company', city: 'París', country: 'Francia',
    lat: 48.8530, lng: 2.3479, category: 'otro',
    description: 'La librería anglofona más famosa del mundo (1951, heredera de la de Sylvia Beach de 1919): laberinto de estanterías con el piano de pie, gatos, cafetería adjunta y el lema "Kilometres零 Zero". Fitzgerald, Hemingway y Joyce pasaron por la original.',
    highlights: 'Piano de pie, cat "Aggie", reading library arriba, sello "Shakespeare and Company" gratis en compras, café adjunto, paso del Petit Pont al lado.',
    opening_hours: 'Todos los días 10:00–22:00 aprox. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis entrar; fila en temporada alta. Comprar un libro para el sello.',
    price: 'Gratis (libros aparte)',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'A 2 min de Notre-Dame. Comprar una novela del viaje es tradición familiar.',
    added_by: 'Precarga',
  },
  {
    name: 'Arte urbano de Belleville', city: 'París', country: 'Francia',
    lat: 48.8722, lng: 2.3830, category: 'paseo_barrio',
    description: 'El barrio de inmigración y contracultura convertido en capital del street art parisino: murales gigantes, collages y graffiti por Rue Denoyez, el Parc de Belleville y las escaleras del Rue du Transvaal.',
    highlights: 'Rue Denoyez (galería al aire libre), murales de la Rue de Belleville, Parc de Belleville con vista de la Torre Eiffel, talleres abiertos, áticos chinos y norteafricanos.',
    opening_hours: 'Siempre accesible (barrio).',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Combinar con Buttes-Chaumont. Vista panorámica del Parc de Belleville gratis y sin colas.',
    added_by: 'Precarga',
  },
  {
    name: 'Murales del distrito 13', city: 'París', country: 'Francia',
    lat: 48.8280, lng: 2.3720, category: 'paseo_barrio',
    description: 'El Boulevard Vincent Auriol y alrededores, galería de street art a cielo abierto del 13º: murales de Inti, Jaz, D*Face, Seth, Obey y decenas más, renovados cada año por la galería Itinerrance.',
    highlights: 'Mural de Inti (Semíramis), D*Face, Seth (niños), Obey, murales de la Rue Jeanne d\'Arc, boulevard Vincent Auriol.',
    opening_hours: 'Siempre accesible (calles).',
    reservation_required: false,
    reservation_notes: 'Gratis.',
    price: 'Gratis',
    assigned_date: '2026-12-31', must_see: false,
    notes: 'Metro Nationale o BnF. También el Palais de Tokyo y la Fondation Louis Vuitton tienen arte urbano.',
    added_by: 'Precarga',
  },
  {
    name: 'Le Marais', city: 'París', country: 'Francia',
    lat: 48.8590, lng: 2.3600, category: 'paseo_barrio',
    description: 'El barrio medieval de moda: hoteles particulares, Place des Vosges (la plaza más antigua de París), boutiques, falafel en Rue des Rosiers, el Musée Picasso y la Place de la République cerca.',
    highlights: 'Place des Vosges, Rue des Rosiers (Judería), Marché des Enfants Rouges (mercado más antiguo), Musée Picasso, Hôtel de Sully, boutiques vintage.',
    opening_hours: 'Siempre accesible (barrio).',
    reservation_required: false,
    reservation_notes: 'Gratis pasear.',
    price: 'Gratis',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Fallas en Rue des Rosiers los domingos. Helado Amorino o Berthillon (isla Saint-Louis al lado).',
    added_by: 'Precarga',
  },
  {
    name: 'Rue Montorgueil', city: 'París', country: 'Francia',
    lat: 48.8673, lng: 2.3472, category: 'comida',
    description: 'Calle peatonal gastronómica del segundo distrito desde el siglo XIV: pescaderías, fromageries, boulangeries, la pâtisserie Stohrer (1730, la más antigua de París) y bistrós con terraza todo el día.',
    highlights: 'Stohrer (invento del baba au rhum), La Maison des Colporteurs, charcuterías, ostras y vino al paseo, ambiente parisino auténtico.',
    opening_hours: 'Tiendas ~8:00–20:00; restaurantes hasta la noche. Verificar antes del viaje.',
    reservation_required: false,
    reservation_notes: 'Gratis pasear; comer según presupuesto.',
    price: '€ (según consumo)',
    assigned_date: '2026-12-29', must_see: false,
    notes: 'Ideal para desayuno o merienda. Cerca de Pompidou y Les Halles.',
    added_by: 'Precarga',
  },

  // ───────────────────────── MADRID ─────────────────────────
  {
    name: 'Madrid · llegada y vuelta (referencia)', city: 'Madrid', country: 'España',
    lat: 40.4168, lng: -3.7038, category: 'otro',
    description: 'Nodo del viaje: llegada el 26 de diciembre, vuelo a París el 27, regreso de Roma el 9 de enero (18:30) y salida final a Medellín el 10 (15:30). Hoteles, restaurantes y paseos por concretar según tiempos de escala.',
    highlights: 'Por definir según horarios finales de vuelos y hotel.',
    opening_hours: '—',
    reservation_required: false,
    reservation_notes: '',
    price: '—',
    assigned_date: null, must_see: false,
    notes: 'Día 26 y 9-10 ene: días de transición. Reservar traslado aeropuerto y hotel.',
    added_by: 'Precarga',
  },
]
